### ISSUE TITLE
Tag for emails

### ISSUE THREAD

**Issue by clh021** [skx/rss2email#94] opened 2022-04-29 07:41 UTC
I want to add a tag to be a grouping or tagging, some types of content I want to focus on and some to read when I have time.

I want to show `tag` before email Subject.

I know I can edit some email.template for every feedlinks but it`s not a good idea.

Maybe feeds.txt like that:

feeds.txt
```
https://rss.url/feed1
 - Tag:feed1
https://rss.url/feed2
 - Tag:feed2
```

But I don't know much about golang.
Have a better idea?

**Comment by skx** [comment] 2022-04-29 08:00
That's an interesting idea, which wouldn't be too hard to add.

I'd expect the end result would be the default template would look like this:

```
Subject: [rss2email]{{if .Tag}} {{.Tag}}{{end}} {{.Subject}}
```

**Comment by clh021** [comment] 2022-04-29 08:15
I'll try to implement this feature in the next few days, hopefully it works. I want to keep your great coding style as much as possible, so I may need to invite you to suggest improvements to my code when I make a new merge request.

**Comment by skx** [comment] 2022-04-29 09:06
OK :)

Should be simple:

* Update feeditem to add "Tag string" here:
  * https://github.com/skx/rss2email/blob/master/withstate/feeditem.go#L29
* In the processor look at the way we iterate over the configuration-file entries.
  * In [this loop](https://github.com/skx/rss2email/blob/master/processor/processor.go#L163).
* But the real change will be in [processFeed](https://github.com/skx/rss2email/blob/830a78ab2eaa1a8cab8b419f08d592a0cc7087a8/processor/processor.go#L230)
  * At the top loop over the config-file to see if there is "Tag" in the options.  If so save the value - using the previous reference as an example.
  * Later when the feeditem is created, set the tag-value if one was found.
     * Somewhere [around here](https://github.com/skx/rss2email/blob/830a78ab2eaa1a8cab8b419f08d592a0cc7087a8/processor/processor.go#L263)   

Finally update the template in `template/template.txt`, to use `Tag` if it is set.

**Comment by skx** [comment] 2022-04-29 09:08
Actually that will not work - the text/template isn't rendered until later!  Oops.

I'll leave the previous comment there, because it does have some value, but it'll need a bigger change after all :)

**Comment by StayPirate** [comment] 2022-05-02 07:17
That's a nice idea and having it available in the feeds file would be very handy. I'm wondering if the Tag header will works good with tags in MUAs? Instead, I think you should apply such a logic within your mailbox. The way I do that is by leveraging dedicated sieve rules. [Here](https://github.com/StayPirate/sieve-susede/blob/49b1781691547533b00fad366742653b452b4d66/10-Tools/10-Bugzilla.sieve#L235-L241) is an example from my personal sieve scripts.

IOW: is the received Tag header shown as tag/flag in the MUA? I use Thunderbird, and I see tags in the following way, but those are not taken from any `Tag` header.

![image](https://user-images.githubusercontent.com/37073343/166197879-8b6cc689-612c-4aa1-8e79-c1351b56efb0.png)

**Comment by StayPirate** [comment] 2022-05-02 07:25
> I want to show `tag` before email Subject.

Sorry, I just got you want to pre-append the Tag on the Subject. That's gonna work for sure.

Anyway, you could even add the wanted tags into a custom header (e.g. `RSS-Tags`), and then make a dedicated sieve rule to apply its value as IMAP-flags (AKA email tags) to the incoming email notification.

**Comment by skx** [comment] 2022-05-03 08:39
@clh021 - did you make any progress, or get stuck?  I'd be happy to implement the change if you're finding it too hard right now.

**Comment by skx** [comment] 2022-05-04 03:21
Closed in #99.

**Closed by skx** 2022-05-04 03:21 UTC

**Comment by StayPirate** [comment] 2022-05-04 11:19
Just for completeness I want to add here the [sieve rule](https://github.com/StayPirate/sieve-susede/blob/34b1299580d0af6131f25d4fdd2f1087820bc451/40-Feeds/40-crazybyte-security-feed.sieve#L52-L59) I'm currently using to convert this new tag field to imap-flags:
```
# rule:[convert X-RSS-Tags to IMAP-flags]
# This rule takes the whole string in the header X-RSS-Tags and use it to set IMAP-flags.
# The string is expected to be either a single word or multiple words separated by a single space.
if exists "X-RSS-Tags" {
    if header :matches "X-RSS-Tags" "*" {
        addflag "${1}";
    }
}
```

The `X-RSS-Tags` header can be set via a custom template, like [this one](https://github.com/StayPirate/rss2email/blob/e6ff431ba100955e5c51e906af96a5c84658afe3/custom_config/templates/default.tmpl#L32).
```
{{if .Tag}}X-RSS-Tags: {{.Tag}}{{end}}
```
It works with a single tag
```
# Github Security Blog
https://github.blog/category/security/feed/feed
- template: /templates/default.tmpl
- tag: tag1
```
or with multiple, separated with a space
```
# Github Security Blog
https://github.blog/category/security/feed/feed
- template: /templates/default.tmpl
- tag: tag1 tag2
```

**Comment by skx** [comment] 2022-05-04 11:32
That's a good comment, I guess I should add the header to the default template - doing that won't add any harm, and it'd safe you from needing a custom one just for this addition.

**Comment by clh021** [comment] 2022-05-04 23:35
Hi, I'm sorry I didn't see your message.
I have tried to implement this function during this holiday, and the core modification is as follows:
https://github.com/clh021/rss2email/commit/669e93ecdbcd8c32405d2ea3edf7f70d571f2166
https://github.com/clh021/rss2email/commit/fc1fe5197a235fcbf526f82ea990969833404f3b
When I'm done, I'm going to write the tests and then submit a merge request to you. But I found that I don`t know who to write the corresponding test ●﹏●. I had to compile the program and try it out for a few days.

I've been so busy in the last few days of this vacation, and luckily the new program I compiled works well😃. Today is a business day, so I only see your message now. I'm really sorry.

It's worth mentioning that in the process of implementing the tag feature, I expected the template to apply more user-defined fields. In this way, the presentation of the template will be more flexible. For details, you can refer to my modified code. Thank you for contributing such a useful and neat application.

——————————————————————————————

您好，我很抱歉没有看到您的消息。
我在这次假期有尝试实现此功能，核心修改如下：
https://github.com/clh021/rss2email/commit/669e93ecdbcd8c32405d2ea3edf7f70d571f2166
https://github.com/clh021/rss2email/commit/fc1fe5197a235fcbf526f82ea990969833404f3b
我写完之后，打算编写好测试然后再给您提交合并请求。但是我发现我不会写对应的测试●﹏●。我只好先编译好程序自己试用几天。

在这次假期的最后几天我太忙了，幸运的是我编译的新程序运作良好😃。今天是工作日，所以我现在才看到您的信息。真的很抱歉。

值得一提的是，我在实现 tag 特性的过程中，期望模板 可以应用更多用户自定义字段。这样模板的展现方式将会更加灵活。具体您可以参看我修改的代码。感谢您贡献出了如此好用又精巧的应用程序！

**Comment by StayPirate** [comment] 2022-05-05 10:46
> That's a good comment, I guess I should add the header to the default template - doing that won't add any harm, and it'd safe you from needing a custom one just for this addition.

I just noticed that this solution introduce an empty line in the email headers when no tag is specified:
```
[...]
Message-Id: <20220505104304.534DF13B11@imap2.suse-dmz.suse.de>
Date: Thu,  5 May 2022 10:43:04 +0000 (UTC)

X-RSS-Link: https://bodhi.fedoraproject.org/updates/FEDORA-2022-bc5c8ee61e
X-RSS-Feed: https://bodhi.fedoraproject.org/rss/updates/?search=&status=stable&type=security
[...]
```
which is **not causing any problem** at all. Anyway, I'm wondering if that can be avoided by changing the template file?

**Comment by StayPirate** [comment] 2022-05-06 07:27
> which is **not causing any problem** at all. Anyway, I'm wondering if that can be avoided by changing the template file?

I need to correct my previous statement, **THIS IS a problem**. It seems that as soon as an empty line is found, everything after is no longer considered part of the email headers. If we want to add conditional statements in the template at the header side, then we need to ensure it won't add an empty line when the condition is not satisfied. IOW @skx, https://github.com/skx/rss2email/commit/6a97fa2bef226419fce76b092635a7c170482af5 is introducing a bug.

**Comment by skx** [comment] 2022-05-06 08:28
Yeah a newline will separate the message-header from the message-body.  So if one appears it will break the formatting of the message.

That's the purpose of the "`- `" prefix inside the `{{if...}}` and `{{end}}` blocks in the template, and because of those I cannot reproduce the problem myself.  My emails look fine, without an extra newline with no Tag value set.

Consider this example template:

```
BEFORE
{{- if env "xUSER"}}
{{env "xUSER"}}
{{- end}}
AFTER
```
When I process that I see:

```
BEFORE
AFTER
```

As I would expect.  If I change `xUSER` to `USER` then I get:

```
BEFORE
skx
AFTER
```

Can you confirm that your template looks 100% unchanged from mine?  That it reads:

```
{{- if .Tag}}
X-RSS-Tags: {{.Tag}}
{{- end}}
```

The leading "`- `" part is *very* important.  I know that you've used a custom template in the past, so if you're using one still that could be a local issue just for you there..

**Comment by StayPirate** [comment] 2022-05-06 10:17
I missed the `- ` when I manually copied your example over to my templates. I now applied it via https://github.com/StayPirate/rss2email/commit/e9d6779c94ebc2282e181e5a31da986afeb8808b and it works like a charm. Thanks mate 👍🏼
